{ config, pkgs, ... }:

{
  imports =
    [ # Include the results of the hardware scan.
      ./hardware-configuration.nix
    ];

  # ============================
  # Boot & Kernel
  # ============================
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;
  
  # LATEST KERNEL (Crucial for new laptop hardware)
  boot.kernelPackages = pkgs.linuxPackages_latest;

  # ============================
  # Networking
  # ============================
  networking.hostName = "nixos-daily"; 
  networking.networkmanager.enable = true;

  # ============================
  # Localization
  # ============================
  time.timeZone = "America/New_York"; # CHANGE THIS to your timezone
  i18n.defaultLocale = "en_US.UTF-8";

  # ============================
  # Desktop Environment (GNOME)
  # ============================
  services.xserver.enable = true;
  services.xserver.displayManager.gdm.enable = true;
  services.xserver.desktopManager.gnome.enable = true;
  
  # Keymap
  services.xserver.xkb = { layout = "us"; variant = ""; };

  # ============================
  # Audio (Pipewire)
  # ============================
  hardware.pulseaudio.enable = false;
  security.rtkit.enable = true;
  services.pipewire = {
    enable = true;
    alsa.enable = true;
    alsa.support32Bit = true;
    pulse.enable = true;
  };

  # ============================
  # User Account
  # ============================
  users.users.YOUR_USERNAME_HERE = {  # <--- CHANGE THIS
    isNormalUser = true;
    description = "Daily Driver";
    extraGroups = [ "networkmanager" "wheel" "docker" "libvirtd" ];
    # Sets a default password of 'nixos' to ensure you can login first time.
    # Change this immediately after reboot using the 'passwd' command.
    initialPassword = "nixos"; 
  };

  # ============================
  # Software & Packages
  # ============================
  nixpkgs.config.allowUnfree = true;

  environment.systemPackages = with pkgs; [
    vim
    wget
    git
    htop
    brave
    vscode
    
    # Virtualization Tools
    qemu_full
    virt-manager
    docker-compose
    swtpm       # TPM for Windows 11
    OVMFFull    # UEFI for Windows 11
  ];

  # ============================
  # Virtualization Config
  # ============================
  
  # Docker
  virtualisation.docker.enable = true;

  # KVM / QEMU / Virt-Manager
  virtualisation.libvirtd = {
    enable = true;
    qemu = {
      package = pkgs.qemu_full;
      runAsRoot = true;
      swtpm.enable = true;
      ovmf = {
        enable = true;
        packages = [(pkgs.OVMF.override {
          secureBoot = true;
          tpmSupport = true;
        }).fd];
      };
    };
  };
  
  programs.dconf.enable = true; # Needed for virt-manager settings
  virtualisation.spiceUSBRedirection.enable = true;

  # ============================
  # System Version
  # ============================
  # Keep this same as the one generated by the installer!
  system.stateVersion = "25.11"; 
}
